const mongoose = require('mongoose');
const PendingNews = require('../models/PendingNews');
require('dotenv').config();

// Sample news data with different dates for testing
const sampleNews = [
  {
    title: 'Test Article 1 - January 2025',
    titleEn: 'Test Article 1 - January 2025',
    excerpt: 'This is a test article from January 2025 to test the archived news section.',
    excerptEn: 'This is a test article from January 2025 to test the archived news section.',
    content: '<p>Full content for test article 1 from January 2025.</p>',
    contentEn: '<p>Full content for test article 1 from January 2025.</p>',
    category: 'National',
    tags: ['test', 'january'],
    pages: ['home', 'national'],
    author: 'Test Author',
    isBreaking: false,
    isFeatured: false,
    isTrending: false,
    generatedBy: 'manual',
    createdAt: new Date('2025-01-15T10:00:00Z'),
    updatedAt: new Date('2025-01-15T10:00:00Z'),
    generatedAt: new Date('2025-01-15T10:00:00Z')
  },
  {
    title: 'Test Article 2 - February 2025',
    titleEn: 'Test Article 2 - February 2025',
    excerpt: 'This is a test article from February 2025 to test the archived news section.',
    excerptEn: 'This is a test article from February 2025 to test the archived news section.',
    content: '<p>Full content for test article 2 from February 2025.</p>',
    contentEn: '<p>Full content for test article 2 from February 2025.</p>',
    category: 'International',
    tags: ['test', 'february'],
    pages: ['home', 'international'],
    author: 'Test Author',
    isBreaking: false,
    isFeatured: false,
    isTrending: false,
    generatedBy: 'manual',
    createdAt: new Date('2025-02-10T10:00:00Z'),
    updatedAt: new Date('2025-02-10T10:00:00Z'),
    generatedAt: new Date('2025-02-10T10:00:00Z')
  },
  {
    title: 'Test Article 3 - March 2025',
    titleEn: 'Test Article 3 - March 2025',
    excerpt: 'This is a test article from March 2025 to test the archived news section.',
    excerptEn: 'This is a test article from March 2025 to test the archived news section.',
    content: '<p>Full content for test article 3 from March 2025.</p>',
    contentEn: '<p>Full content for test article 3 from March 2025.</p>',
    category: 'Sports',
    tags: ['test', 'march'],
    pages: ['home', 'sports'],
    author: 'Test Author',
    isBreaking: false,
    isFeatured: false,
    isTrending: false,
    generatedBy: 'manual',
    createdAt: new Date('2025-03-05T10:00:00Z'),
    updatedAt: new Date('2025-03-05T10:00:00Z'),
    generatedAt: new Date('2025-03-05T10:00:00Z')
  },
  {
    title: 'Test Article 4 - April 2025',
    titleEn: 'Test Article 4 - April 2025',
    excerpt: 'This is a test article from April 2025 to test the archived news section.',
    excerptEn: 'This is a test article from April 2025 to test the archived news section.',
    content: '<p>Full content for test article 4 from April 2025.</p>',
    contentEn: '<p>Full content for test article 4 from April 2025.</p>',
    category: 'Business',
    tags: ['test', 'april'],
    pages: ['home', 'business'],
    author: 'Test Author',
    isBreaking: false,
    isFeatured: false,
    isTrending: false,
    generatedBy: 'manual',
    createdAt: new Date('2025-04-20T10:00:00Z'),
    updatedAt: new Date('2025-04-20T10:00:00Z'),
    generatedAt: new Date('2025-04-20T10:00:00Z')
  },
  {
    title: 'Test Article 5 - May 2025',
    titleEn: 'Test Article 5 - May 2025',
    excerpt: 'This is a test article from May 2025 to test the archived news section.',
    excerptEn: 'This is a test article from May 2025 to test the archived news section.',
    content: '<p>Full content for test article 5 from May 2025.</p>',
    contentEn: '<p>Full content for test article 5 from May 2025.</p>',
    category: 'Entertainment',
    tags: ['test', 'may'],
    pages: ['home', 'entertainment'],
    author: 'Test Author',
    isBreaking: false,
    isFeatured: false,
    isTrending: false,
    generatedBy: 'manual',
    createdAt: new Date('2025-05-12T10:00:00Z'),
    updatedAt: new Date('2025-05-12T10:00:00Z'),
    generatedAt: new Date('2025-05-12T10:00:00Z')
  },
  {
    title: 'Test Article 6 - June 2025',
    titleEn: 'Test Article 6 - June 2025',
    excerpt: 'This is a test article from June 2025 to test the archived news section.',
    excerptEn: 'This is a test article from June 2025 to test the archived news section.',
    content: '<p>Full content for test article 6 from June 2025.</p>',
    contentEn: '<p>Full content for test article 6 from June 2025.</p>',
    category: 'Health',
    tags: ['test', 'june'],
    pages: ['home', 'health'],
    author: 'Test Author',
    isBreaking: false,
    isFeatured: false,
    isTrending: false,
    generatedBy: 'manual',
    createdAt: new Date('2025-06-18T10:00:00Z'),
    updatedAt: new Date('2025-06-18T10:00:00Z'),
    generatedAt: new Date('2025-06-18T10:00:00Z')
  },
  {
    title: 'Test Article 7 - July 2025',
    titleEn: 'Test Article 7 - July 2025',
    excerpt: 'This is a test article from July 2025 to test the archived news section.',
    excerptEn: 'This is a test article from July 2025 to test the archived news section.',
    content: '<p>Full content for test article 7 from July 2025.</p>',
    contentEn: '<p>Full content for test article 7 from July 2025.</p>',
    category: 'Politics',
    tags: ['test', 'july'],
    pages: ['home', 'politics'],
    author: 'Test Author',
    isBreaking: false,
    isFeatured: false,
    isTrending: false,
    generatedBy: 'manual',
    createdAt: new Date('2025-07-25T10:00:00Z'),
    updatedAt: new Date('2025-07-25T10:00:00Z'),
    generatedAt: new Date('2025-07-25T10:00:00Z')
  },
  {
    title: 'Test Article 8 - August 2025',
    titleEn: 'Test Article 8 - August 2025',
    excerpt: 'This is a test article from August 2025 to test the archived news section.',
    excerptEn: 'This is a test article from August 2025 to test the archived news section.',
    content: '<p>Full content for test article 8 from August 2025.</p>',
    contentEn: '<p>Full content for test article 8 from August 2025.</p>',
    category: 'Religious',
    tags: ['test', 'august'],
    pages: ['home', 'religious'],
    author: 'Test Author',
    isBreaking: false,
    isFeatured: false,
    isTrending: false,
    generatedBy: 'manual',
    createdAt: new Date('2025-08-08T10:00:00Z'),
    updatedAt: new Date('2025-08-08T10:00:00Z'),
    generatedAt: new Date('2025-08-08T10:00:00Z')
  },
  {
    title: 'Test Article 9 - September 2025',
    titleEn: 'Test Article 9 - September 2025',
    excerpt: 'This is a test article from September 2025 to test the archived news section.',
    excerptEn: 'This is a test article from September 2025 to test the archived news section.',
    content: '<p>Full content for test article 9 from September 2025.</p>',
    contentEn: '<p>Full content for test article 9 from September 2025.</p>',
    category: 'National',
    tags: ['test', 'september'],
    pages: ['home', 'national'],
    author: 'Test Author',
    isBreaking: false,
    isFeatured: false,
    isTrending: false,
    generatedBy: 'manual',
    createdAt: new Date('2025-09-14T10:00:00Z'),
    updatedAt: new Date('2025-09-14T10:00:00Z'),
    generatedAt: new Date('2025-09-14T10:00:00Z')
  },
  {
    title: 'Test Article 10 - October 2025',
    titleEn: 'Test Article 10 - October 2025',
    excerpt: 'This is a test article from October 2025 to test the archived news section.',
    excerptEn: 'This is a test article from October 2025 to test the archived news section.',
    content: '<p>Full content for test article 10 from October 2025.</p>',
    contentEn: '<p>Full content for test article 10 from October 2025.</p>',
    category: 'International',
    tags: ['test', 'october'],
    pages: ['home', 'international'],
    author: 'Test Author',
    isBreaking: false,
    isFeatured: false,
    isTrending: false,
    generatedBy: 'manual',
    createdAt: new Date('2025-10-30T10:00:00Z'),
    updatedAt: new Date('2025-10-30T10:00:00Z'),
    generatedAt: new Date('2025-10-30T10:00:00Z')
  },
  {
    title: 'Test Article 11 - November 2025',
    titleEn: 'Test Article 11 - November 2025',
    excerpt: 'This is a test article from November 2025 to test the archived news section.',
    excerptEn: 'This is a test article from November 2025 to test the archived news section.',
    content: '<p>Full content for test article 11 from November 2025.</p>',
    contentEn: '<p>Full content for test article 11 from November 2025.</p>',
    category: 'Sports',
    tags: ['test', 'november'],
    pages: ['home', 'sports'],
    author: 'Test Author',
    isBreaking: false,
    isFeatured: false,
    isTrending: false,
    generatedBy: 'manual',
    createdAt: new Date('2025-11-22T10:00:00Z'),
    updatedAt: new Date('2025-11-22T10:00:00Z'),
    generatedAt: new Date('2025-11-22T10:00:00Z')
  },
  {
    title: 'Test Article 12 - December 2025',
    titleEn: 'Test Article 12 - December 2025',
    excerpt: 'This is a test article from December 2025 to test the archived news section.',
    excerptEn: 'This is a test article from December 2025 to test the archived news section.',
    content: '<p>Full content for test article 12 from December 2025.</p>',
    contentEn: '<p>Full content for test article 12 from December 2025.</p>',
    category: 'Business',
    tags: ['test', 'december'],
    pages: ['home', 'business'],
    author: 'Test Author',
    isBreaking: false,
    isFeatured: false,
    isTrending: false,
    generatedBy: 'manual',
    createdAt: new Date('2025-12-15T10:00:00Z'),
    updatedAt: new Date('2025-12-15T10:00:00Z'),
    generatedAt: new Date('2025-12-15T10:00:00Z')
  },
  {
    title: 'Test Article 13 - January 2024',
    titleEn: 'Test Article 13 - January 2024',
    excerpt: 'This is a test article from January 2024 to test year filtering.',
    excerptEn: 'This is a test article from January 2024 to test year filtering.',
    content: '<p>Full content for test article 13 from January 2024.</p>',
    contentEn: '<p>Full content for test article 13 from January 2024.</p>',
    category: 'National',
    tags: ['test', '2024'],
    pages: ['home', 'national'],
    author: 'Test Author',
    isBreaking: false,
    isFeatured: false,
    isTrending: false,
    generatedBy: 'manual',
    createdAt: new Date('2024-01-10T10:00:00Z'),
    updatedAt: new Date('2024-01-10T10:00:00Z'),
    generatedAt: new Date('2024-01-10T10:00:00Z')
  },
  {
    title: 'Test Article 14 - February 2024',
    titleEn: 'Test Article 14 - February 2024',
    excerpt: 'This is a test article from February 2024 to test year filtering.',
    excerptEn: 'This is a test article from February 2024 to test year filtering.',
    content: '<p>Full content for test article 14 from February 2024.</p>',
    contentEn: '<p>Full content for test article 14 from February 2024.</p>',
    category: 'International',
    tags: ['test', '2024'],
    pages: ['home', 'international'],
    author: 'Test Author',
    isBreaking: false,
    isFeatured: false,
    isTrending: false,
    generatedBy: 'manual',
    createdAt: new Date('2024-02-20T10:00:00Z'),
    updatedAt: new Date('2024-02-20T10:00:00Z'),
    generatedAt: new Date('2024-02-20T10:00:00Z')
  },
  {
    title: 'Test Article 15 - March 2024',
    titleEn: 'Test Article 15 - March 2024',
    excerpt: 'This is a test article from March 2024 to test year filtering.',
    excerptEn: 'This is a test article from March 2024 to test year filtering.',
    content: '<p>Full content for test article 15 from March 2024.</p>',
    contentEn: '<p>Full content for test article 15 from March 2024.</p>',
    category: 'Sports',
    tags: ['test', '2024'],
    pages: ['home', 'sports'],
    author: 'Test Author',
    isBreaking: false,
    isFeatured: false,
    isTrending: false,
    generatedBy: 'manual',
    createdAt: new Date('2024-03-15T10:00:00Z'),
    updatedAt: new Date('2024-03-15T10:00:00Z'),
    generatedAt: new Date('2024-03-15T10:00:00Z')
  },
  {
    title: 'Test Article 16 - January 2026',
    titleEn: 'Test Article 16 - January 2026',
    excerpt: 'This is a test article from January 2026 to test year filtering.',
    excerptEn: 'This is a test article from January 2026 to test year filtering.',
    content: '<p>Full content for test article 16 from January 2026.</p>',
    contentEn: '<p>Full content for test article 16 from January 2026.</p>',
    category: 'Business',
    tags: ['test', '2026'],
    pages: ['home', 'business'],
    author: 'Test Author',
    isBreaking: false,
    isFeatured: false,
    isTrending: false,
    generatedBy: 'manual',
    createdAt: new Date('2026-01-05T10:00:00Z'),
    updatedAt: new Date('2026-01-05T10:00:00Z'),
    generatedAt: new Date('2026-01-05T10:00:00Z')
  },
  {
    title: 'Test Article 17 - February 2026',
    titleEn: 'Test Article 17 - February 2026',
    excerpt: 'This is a test article from February 2026 to test year filtering.',
    excerptEn: 'This is a test article from February 2026 to test year filtering.',
    content: '<p>Full content for test article 17 from February 2026.</p>',
    contentEn: '<p>Full content for test article 18 from February 2026.</p>',
    category: 'Entertainment',
    tags: ['test', '2026'],
    pages: ['home', 'entertainment'],
    author: 'Test Author',
    isBreaking: false,
    isFeatured: false,
    isTrending: false,
    generatedBy: 'manual',
    createdAt: new Date('2026-02-14T10:00:00Z'),
    updatedAt: new Date('2026-02-14T10:00:00Z'),
    generatedAt: new Date('2026-02-14T10:00:00Z')
  },
  {
    title: 'Test Article 18 - March 2026',
    titleEn: 'Test Article 18 - March 2026',
    excerpt: 'This is a test article from March 2026 to test year filtering.',
    excerptEn: 'This is a test article from March 2026 to test year filtering.',
    content: '<p>Full content for test article 18 from March 2026.</p>',
    contentEn: '<p>Full content for test article 18 from March 2026.</p>',
    category: 'Health',
    tags: ['test', '2026'],
    pages: ['home', 'health'],
    author: 'Test Author',
    isBreaking: false,
    isFeatured: false,
    isTrending: false,
    generatedBy: 'manual',
    createdAt: new Date('2026-03-01T10:00:00Z'),
    updatedAt: new Date('2026-03-01T10:00:00Z'),
    generatedAt: new Date('2026-03-01T10:00:00Z')
  },
  {
    title: 'Test Article 19 - April 2026',
    titleEn: 'Test Article 19 - April 2026',
    excerpt: 'This is a test article from April 2026 to test year filtering.',
    excerptEn: 'This is a test article from April 2026 to test year filtering.',
    content: '<p>Full content for test article 19 from April 2026.</p>',
    contentEn: '<p>Full content for test article 19 from April 2026.</p>',
    category: 'Politics',
    tags: ['test', '2026'],
    pages: ['home', 'politics'],
    author: 'Test Author',
    isBreaking: false,
    isFeatured: false,
    isTrending: false,
    generatedBy: 'manual',
    createdAt: new Date('2026-04-10T10:00:00Z'),
    updatedAt: new Date('2026-04-10T10:00:00Z'),
    generatedAt: new Date('2026-04-10T10:00:00Z')
  },
  {
    title: 'Test Article 20 - May 2026',
    titleEn: 'Test Article 20 - May 2026',
    excerpt: 'This is a test article from May 2026 to test year filtering.',
    excerptEn: 'This is a test article from May 2026 to test year filtering.',
    content: '<p>Full content for test article 20 from May 2026.</p>',
    contentEn: '<p>Full content for test article 20 from May 2026.</p>',
    category: 'Religious',
    tags: ['test', '2026'],
    pages: ['home', 'religious'],
    author: 'Test Author',
    isBreaking: false,
    isFeatured: false,
    isTrending: false,
    generatedBy: 'manual',
    createdAt: new Date('2026-05-25T10:00:00Z'),
    updatedAt: new Date('2026-05-25T10:00:00Z'),
    generatedAt: new Date('2026-05-25T10:00:00Z')
  }
];

async function seedTestArchivedNews() {
  try {
    console.log('🔌 Connecting to MongoDB...');
    await mongoose.connect(process.env.MONGODB_URI || 'mongodb://localhost:27017/newsaddaindia');
    console.log('✅ Connected to MongoDB\n');

    console.log('🗑️  Clearing existing test articles...');
    const deleteResult = await PendingNews.deleteMany({ 
      title: { $regex: /^Test Article/ } 
    });
    console.log(`   Deleted ${deleteResult.deletedCount} existing test articles\n`);

    console.log('📝 Inserting 20 test articles...\n');
    const inserted = await PendingNews.insertMany(sampleNews);
    
    console.log(`✅ Successfully inserted ${inserted.length} test articles!\n`);
    console.log('📊 Summary:');
    console.log(`   - Articles from 2024: ${sampleNews.filter(n => n.createdAt.getFullYear() === 2024).length}`);
    console.log(`   - Articles from 2025: ${sampleNews.filter(n => n.createdAt.getFullYear() === 2025).length}`);
    console.log(`   - Articles from 2026: ${sampleNews.filter(n => n.createdAt.getFullYear() === 2026).length}`);
    console.log('\n🎉 Test data seeded successfully!');
    console.log('   You can now test the archived news section with year/month filters.\n');

    await mongoose.connection.close();
    console.log('✅ Database connection closed');
    process.exit(0);
  } catch (error) {
    console.error('❌ Error seeding test data:', error);
    process.exit(1);
  }
}

seedTestArchivedNews();
